package com.xelari.presencebot.telegram.operation.callback;

public enum CallbackType {
    CREATE_TEAM,

    INVITE_MEMBER,
    INVITE_MEMBER_SELECT_ROLE,
    INVITE_MEMBER_GENERATE_TOKEN,

    ENTER_TEAM,

    CREATE_MEETING_SELECT_TEAM,
    CHANGE_MEETING_SELECT_TEAM,

    CREATE_MEETING_TEAM_SELECTED,

    CREATE_MEETING_REPEAT_NONE,
    CREATE_MEETING_REPEAT_EVERY_DAY,
    CREATE_MEETING_REPEAT_EVERY_WEEK,
    CREATE_MEETING_REPEAT_EVERY_MONTH

}
