package com.xelari.presencebot.telegram.operation.callback;

public enum CallbackType {
    CREATE_TEAM,

    INVITE_MEMBER,
    INVITE_MEMBER_SELECT_ROLE,
    INVITE_MEMBER_GENERATE_TOKEN,

    ENTER_TEAM,

    CREATE_MEETING,
    CHANGE_MEETING,
    SHOW_MY_MEETINGS,

    CREATE_MEETING_TEAM_SELECTED,
    CREATE_MEETING_ADD_DESCRIPTION,
    CREATE_MEETING_DONT_ADD_DESCRIPTION,
    CREATE_MEETING_REPEAT_SELECTED,

    SHOW_MEETINGS_ALL_MEETINGS,
    SHOW_MEETINGS_FOR_TEAM,
    SHOW_MEETINGS_WITH_SELECTED_TEAM,

    CHANGE_MEETING_DELETE,
    CHANGE_MEETING_CHANGE_TIME,
    CHANGE_MEETING_SELECT_MEETING,
}
