spring:

  application:
    name: presence-bot

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:presenceDev}?createDatabaseIfNotExist=true
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PresenceBotPool
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false

  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      # ddl-auto: create
      ddl-auto: update

    properties:
  #    hibernate.default_schema: ${POSTGRES_SCHEMA:pins}
     hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog.yaml

  # liquibase:
  #   default-schema: ${POSTGRES_SCHEMA:pins}
  #   change-log: classpath:/${POSTGRES_SCHEMA:pins}/master.yml
  #   database-change-log-table: _databasechangelog
  #   database-change-log-lock-table: _databasechangeloglock

cloud:
  aws:
    credentials:
      accessKey: ${MINIO_ROOT_USER}
      secretKey: ${MINIO_ROOT_PASSWORD}
    s3:
      bucket: my-bucket
    region:
      static: eu-west-2

amazon:
  s3:
    endpoint: http://localhost:9000
    path-style-access: true
    disable-chunked-encoding: true

bot:
  name:"Xelari-presence-bot"
  token:${BOT_TOKEN}

invitation:
  token-expiration-days: 1

meeting:
  reminder:
    check-interval-ms: 60_000
    № check-interval-ms: 600
    notification-interval-minutes: 30