version: '3.8'

services:

  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    ports:
      - "5433:5432"
    env_file: ../env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  presence-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: presence-bot
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: ../env/.env
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - ../env:/app/env:ro
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # S3 API port
      - "9001:9001"     # Web console
    env_file: ../env/.env
    volumes:
      - minio_data:/data
    command: [ "server", "/data", "--console-address", ":9001" ]

volumes:

  postgres_data:

  minio_data: