version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - ../env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../env/.env
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  postgres_data:
  minio_data: