version: '3.8'

services:
  presence-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: presence-bot
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:8080"
    env_file:
      - ../env/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres # TODO: check if it works
      TZ: UTC
    volumes:
      - ../env:/app/env:ro
      - logs:/var/logs/presence-bot
    restart: always

volumes:
  logs: