version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: postgres
    ports:
      - "5433:5432"
    env_file: ../env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  presence-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: presence-bot
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: ../env/.env
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - ../env:/app/env:ro
    restart: unless-stopped

volumes:
  postgres_data: