services:
  presence-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: presence-bot
#     depends_on:
#       postgres:
#         condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: host.docker.internal
      MINIO_HOST: host.docker.internal
    volumes:
      - ../env:/app/env:ro
    restart: unless-stopped